services:
  config-server-e-learning-platform:
    image: "config-server-e-learning-platform"
    container_name: "config-server-e-learning-platform"
    environment:
      - THC_PATH=/actuator/health
      - THC_PORT=9095
    ports:
      - "9095:9095"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  enrollment-service:
    image: "enrollment-service"
    container_name: "enrollment-service"
    depends_on:
      postgres-enrollments:
        condition: service_healthy
      config-server-e-learning-platform:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      - CONFIGSERVER_IMPORT=configserver:${CONFIG_SERVER_URL}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USER=${ENROLLMENTS_DB_USER}
      - DB_PASSWORD=${ENROLLMENTS_DB_PASSWORD}
      - DB_URL=${ENROLLMENTS_DB_URL}
      - FLYWAY_DB_URL=${ENROLLMENTS_DB_FLYWAY_URL}
      - COURSE_SERVICE_URL=${COURSE_SERVICE_URL}

  course-service:
    image: "course-service"
    container_name: "course-service"
    depends_on:
      postgres-courses:
        condition: service_healthy
      config-server-e-learning-platform:
        condition: service_healthy
    ports:
      - "9091:9091"
    environment:
      - CONFIGSERVER_IMPORT=configserver:${CONFIG_SERVER_URL}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USER=${COURSE_DB_USER}
      - DB_PASSWORD=${COURSE_DB_PASSWORD}
      - DB_URL=${COURSE_DB_URL}

  postgres-courses:
    image: "postgres:16.1"
    container_name: "postgres-courses"
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_USER=${COURSE_DB_USER}
      - POSTGRES_PASSWORD=${COURSE_DB_PASSWORD}
      - POSTGRES_DB=course_service_db
      - PGPORT=5431
    volumes:
      - db-courses:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready",  "-d", "course_service_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  postgres-enrollments:
    image: "postgres:16.1"
    container_name: "postgres-enrollments"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${ENROLLMENTS_DB_USER}
      - POSTGRES_PASSWORD=${ENROLLMENTS_DB_PASSWORD}
      - POSTGRES_DB=enrollment_service_db
    volumes:
      - db-enrollments:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "enrollment_service_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db-enrollments:
    driver: local
  db-courses:
    driver: local
